server.port=${servicePort}
spring.application.name=${serviceName}

# URLs de microservicios
services.inventory.url=http://localhost:4001
services.orders.url=http://localhost:4002
services.shipping.url=http://localhost:4003
services.payment.url=http://localhost:4004

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
